In [17]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn import datasets
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from numpy import genfromtxt

X = genfromtxt('7_25.csv', delimiter=',')

pca = PCA(n_components=2, svd_solver='full') #Создание объекта класса PCA. В качестве параметров выступает количество ГК и метод оптимизации
X_transformed = pca.fit(X).transform(X) #X_transformed -- ndarray объектов, где каждый объект описывается двумя ГК
X_transformed[0]

array([-32.31442582,  -4.26100973])

Числа, которые получились выше, нужно вставить в первые 2 ячейки ответа ("Введите координату первого объекта относительно первой главной компоненты" и "Введите координату первого объекта относительно второй главной компоненты")

In [18]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn import datasets
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from numpy import genfromtxt

X = genfromtxt('7_25.csv', delimiter=',')

pca = PCA(n_components=2, svd_solver='full') #Создание объекта класса PCA. В качестве параметров выступает количество ГК и метод оптимизации
X_transformed = pca.fit(X).transform(X) #X_transformed -- ndarray объектов, где каждый объект описывается двумя ГК

explained_variance = np.round(np.cumsum(pca.explained_variance_ratio_),3)
explained_variance

array([0.421, 0.69 ])

В третью ячейу ответа нужно ввести только ВТОРОЕ число массива.

In [19]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn import datasets
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from numpy import genfromtxt

X = genfromtxt('7_25.csv', delimiter=',')

pca = PCA(n_components=3, svd_solver='full') #Создание объекта класса PCA. В качестве параметров выступает количество ГК и метод оптимизации
X_transformed = pca.fit(X).transform(X) #X_transformed -- ndarray объектов, где каждый объект описывается двумя ГК

explained_variance = np.round(np.cumsum(pca.explained_variance_ratio_),3)
explained_variance

array([0.421, 0.69 , 0.931])

Далее по заданию нам укажут число (доля объясненной дисперсии).

В строке: pca = PCA(n_components=3, svd_solver='full')

надо увеличивать n_components до тех пор, пока последний элемент массива не станет больше того чамого числа в задании.

Ответом будет значение n_components.